var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":121,"id":583,"methods":[{"el":29,"sc":3,"sl":26},{"el":34,"sc":3,"sl":31},{"el":39,"sc":3,"sl":36},{"el":44,"sc":3,"sl":41},{"el":49,"sc":3,"sl":46},{"el":54,"sc":3,"sl":51},{"el":59,"sc":3,"sl":56},{"el":64,"sc":3,"sl":61},{"el":69,"sc":3,"sl":66},{"el":74,"sc":3,"sl":71},{"el":79,"sc":3,"sl":76},{"el":84,"sc":3,"sl":81},{"el":89,"sc":3,"sl":86},{"el":94,"sc":3,"sl":91},{"el":99,"sc":3,"sl":96},{"el":104,"sc":3,"sl":101},{"el":109,"sc":3,"sl":106},{"el":114,"sc":3,"sl":111},{"el":120,"sc":3,"sl":116}],"name":"BeanMatchersTest","sl":24}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_10":{"methods":[{"sl":101}],"name":"testHasValidBeanToStringExcluding","pass":true,"statements":[{"sl":103}]},"test_104":{"methods":[{"sl":36}],"name":"testHasValidGettersAndSettersFor","pass":true,"statements":[{"sl":38}]},"test_105":{"methods":[{"sl":61}],"name":"testHasValidBeanHashCode","pass":true,"statements":[{"sl":63}]},"test_107":{"methods":[{"sl":96}],"name":"testHasValidBeanToString","pass":true,"statements":[{"sl":98}]},"test_120":{"methods":[{"sl":116}],"name":"canRegisterCustomValueGenerator","pass":true,"statements":[{"sl":118},{"sl":119}]},"test_125":{"methods":[{"sl":41}],"name":"testBeanHasValidGettersAndSettersExcluding","pass":true,"statements":[{"sl":43}]},"test_136":{"methods":[{"sl":46}],"name":"testHasValidGettersAndSettersExcluding","pass":true,"statements":[{"sl":48}]},"test_141":{"methods":[{"sl":26}],"name":"testHasValidBeanConstructor","pass":true,"statements":[{"sl":28}]},"test_142":{"methods":[{"sl":31}],"name":"testBeanHasValidGettersAndSettersFor","pass":true,"statements":[{"sl":33}]},"test_154":{"methods":[{"sl":111}],"name":"shouldThrowExceptionOnBeanWithPropertyNeedingCustomValueGenerator","pass":true,"statements":[{"sl":113}]},"test_160":{"methods":[{"sl":81}],"name":"testHasValidBeanEqualsOnNonReflectedEquals","pass":true,"statements":[{"sl":83}]},"test_29":{"methods":[{"sl":71}],"name":"testHasValidBeanHashCodeExcluding","pass":true,"statements":[{"sl":73}]},"test_36":{"methods":[{"sl":86}],"name":"testHasValidBeanEqualsExcluding","pass":true,"statements":[{"sl":88}]},"test_48":{"methods":[{"sl":51}],"name":"testBeanHasValidGettersAndSetters","pass":true,"statements":[{"sl":53}]},"test_52":{"methods":[{"sl":76}],"name":"testHasValidBeanEquals","pass":true,"statements":[{"sl":78}]},"test_76":{"methods":[{"sl":91}],"name":"testHasValidBeanEqualsFor","pass":true,"statements":[{"sl":93}]},"test_9":{"methods":[{"sl":66}],"name":"testHasValidBeanHashCodeFor","pass":true,"statements":[{"sl":68}]},"test_90":{"methods":[{"sl":56}],"name":"testHasValidGettersAndSetters","pass":true,"statements":[{"sl":58}]},"test_96":{"methods":[{"sl":106}],"name":"testHasValidBeanToStringFor","pass":true,"statements":[{"sl":108}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [141], [], [141], [], [], [142], [], [142], [], [], [104], [], [104], [], [], [125], [], [125], [], [], [136], [], [136], [], [], [48], [], [48], [], [], [90], [], [90], [], [], [105], [], [105], [], [], [9], [], [9], [], [], [29], [], [29], [], [], [52], [], [52], [], [], [160], [], [160], [], [], [36], [], [36], [], [], [76], [], [76], [], [], [107], [], [107], [], [], [10], [], [10], [], [], [96], [], [96], [], [], [154], [], [154], [], [], [120], [], [120], [120], [], []]
