var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":16,"id":251,"methods":[{"el":7,"sc":3,"sl":5},{"el":11,"sc":3,"sl":9},{"el":15,"sc":3,"sl":13}],"name":"BeanMatchersException","sl":3}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_121":{"methods":[{"sl":13}],"name":"canCreateExceptionWithCause","pass":true,"statements":[{"sl":14}]},"test_123":{"methods":[{"sl":9}],"name":"beanWithInvalidGetterShouldBeDiagnosed","pass":true,"statements":[{"sl":10}]},"test_148":{"methods":[{"sl":5}],"name":"canCreateExceptionWithMessage","pass":true,"statements":[{"sl":6}]},"test_152":{"methods":[{"sl":5}],"name":"getPropertyShouldThrowExceptionGivenPropertyDoesNotExistOnBean","pass":true,"statements":[{"sl":6}]},"test_154":{"methods":[{"sl":5}],"name":"shouldThrowExceptionOnBeanWithPropertyNeedingCustomValueGenerator","pass":true,"statements":[{"sl":6}]},"test_165":{"methods":[{"sl":9}],"name":"canCreateExceptionWithMessageAndCause","pass":true,"statements":[{"sl":10}]},"test_39":{"methods":[{"sl":5}],"name":"shouldThrowExceptionIfSetterIsMissing","pass":true,"statements":[{"sl":6}]},"test_43":{"methods":[{"sl":5}],"name":"setPropertyShouldThrowExceptionGivenPropertyDoesNotExistOnBean","pass":true,"statements":[{"sl":6}]},"test_44":{"methods":[{"sl":9}],"name":"beanWithoutNoArgsConstructorShouldNotMatch","pass":true,"statements":[{"sl":10}]},"test_60":{"methods":[{"sl":5}],"name":"beanWithMissingSetterShouldNotMatch","pass":true,"statements":[{"sl":6}]},"test_66":{"methods":[{"sl":5}],"name":"beanWithMissingGetterShouldNotMatch","pass":true,"statements":[{"sl":6}]},"test_72":{"methods":[{"sl":5}],"name":"shouldThrowExceptionGivenCannotGenerateTwoDistinctValuesAfterXAttempts","pass":true,"statements":[{"sl":6}]},"test_73":{"methods":[{"sl":5}],"name":"shouldThrowExceptionIfGetterIsMissing","pass":true,"statements":[{"sl":6}]},"test_74":{"methods":[{"sl":5}],"name":"shouldThrowExceptionWhenNoGeneratorRegisteredForTypeAndTypeIsFinal","pass":true,"statements":[{"sl":6}]},"test_81":{"methods":[{"sl":5}],"name":"propertyTypeShouldThrowExceptionGivenPropertyDoesNotExistOnBean","pass":true,"statements":[{"sl":6}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [74, 148, 39, 43, 60, 66, 81, 152, 72, 73, 154], [74, 148, 39, 43, 60, 66, 81, 152, 72, 73, 154], [], [], [44, 123, 165], [44, 123, 165], [], [], [121], [121], [], []]
