var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":106,"id":534,"methods":[{"el":14,"sc":5,"sl":11},{"el":19,"sc":5,"sl":16},{"el":24,"sc":5,"sl":21},{"el":29,"sc":5,"sl":26},{"el":34,"sc":5,"sl":31},{"el":39,"sc":5,"sl":36},{"el":44,"sc":5,"sl":41},{"el":49,"sc":5,"sl":46},{"el":54,"sc":5,"sl":51},{"el":59,"sc":5,"sl":56},{"el":64,"sc":5,"sl":61},{"el":69,"sc":5,"sl":66},{"el":74,"sc":5,"sl":71},{"el":79,"sc":5,"sl":76},{"el":84,"sc":5,"sl":81},{"el":89,"sc":5,"sl":86},{"el":94,"sc":5,"sl":91},{"el":99,"sc":5,"sl":96},{"el":105,"sc":5,"sl":101}],"name":"BeanMatchersTest","sl":9}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_116":{"methods":[{"sl":31}],"name":"testHasValidGettersAndSettersExcluding","pass":true,"statements":[{"sl":33}]},"test_12":{"methods":[{"sl":36}],"name":"testBeanHasValidGettersAndSetters","pass":true,"statements":[{"sl":38}]},"test_123":{"methods":[{"sl":66}],"name":"testHasValidBeanEqualsOnNonReflectedEquals","pass":true,"statements":[{"sl":68}]},"test_138":{"methods":[{"sl":46}],"name":"testHasValidBeanHashCode","pass":true,"statements":[{"sl":48}]},"test_141":{"methods":[{"sl":96}],"name":"shouldThrowExceptionOnBeanWithPropertyNeedingCustomValueGenerator","pass":true,"statements":[{"sl":98}]},"test_155":{"methods":[{"sl":56}],"name":"testHasValidBeanHashCodeExcluding","pass":true,"statements":[{"sl":58}]},"test_157":{"methods":[{"sl":41}],"name":"testHasValidGettersAndSetters","pass":true,"statements":[{"sl":43}]},"test_21":{"methods":[{"sl":61}],"name":"testHasValidBeanEquals","pass":true,"statements":[{"sl":63}]},"test_49":{"methods":[{"sl":86}],"name":"testHasValidBeanToStringExcluding","pass":true,"statements":[{"sl":88}]},"test_53":{"methods":[{"sl":51}],"name":"testHasValidBeanHashCodeFor","pass":true,"statements":[{"sl":53}]},"test_55":{"methods":[{"sl":91}],"name":"testHasValidBeanToStringFor","pass":true,"statements":[{"sl":93}]},"test_58":{"methods":[{"sl":21}],"name":"testHasValidGettersAndSettersFor","pass":true,"statements":[{"sl":23}]},"test_60":{"methods":[{"sl":81}],"name":"testHasValidBeanToString","pass":true,"statements":[{"sl":83}]},"test_7":{"methods":[{"sl":76}],"name":"testHasValidBeanEqualsFor","pass":true,"statements":[{"sl":78}]},"test_77":{"methods":[{"sl":101}],"name":"canRegisterCustomValueGenerator","pass":true,"statements":[{"sl":103},{"sl":104}]},"test_80":{"methods":[{"sl":71}],"name":"testHasValidBeanEqualsExcluding","pass":true,"statements":[{"sl":73}]},"test_82":{"methods":[{"sl":16}],"name":"testBeanHasValidGettersAndSettersFor","pass":true,"statements":[{"sl":18}]},"test_84":{"methods":[{"sl":26}],"name":"testBeanHasValidGettersAndSettersExcluding","pass":true,"statements":[{"sl":28}]},"test_85":{"methods":[{"sl":11}],"name":"testHasValidBeanConstructor","pass":true,"statements":[{"sl":13}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [85], [], [85], [], [], [82], [], [82], [], [], [58], [], [58], [], [], [84], [], [84], [], [], [116], [], [116], [], [], [12], [], [12], [], [], [157], [], [157], [], [], [138], [], [138], [], [], [53], [], [53], [], [], [155], [], [155], [], [], [21], [], [21], [], [], [123], [], [123], [], [], [80], [], [80], [], [], [7], [], [7], [], [], [60], [], [60], [], [], [49], [], [49], [], [], [55], [], [55], [], [], [141], [], [141], [], [], [77], [], [77], [77], [], []]
