var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":121,"id":581,"methods":[{"el":29,"sc":3,"sl":26},{"el":34,"sc":3,"sl":31},{"el":39,"sc":3,"sl":36},{"el":44,"sc":3,"sl":41},{"el":49,"sc":3,"sl":46},{"el":54,"sc":3,"sl":51},{"el":59,"sc":3,"sl":56},{"el":64,"sc":3,"sl":61},{"el":69,"sc":3,"sl":66},{"el":74,"sc":3,"sl":71},{"el":79,"sc":3,"sl":76},{"el":84,"sc":3,"sl":81},{"el":89,"sc":3,"sl":86},{"el":94,"sc":3,"sl":91},{"el":99,"sc":3,"sl":96},{"el":104,"sc":3,"sl":101},{"el":109,"sc":3,"sl":106},{"el":114,"sc":3,"sl":111},{"el":120,"sc":3,"sl":116}],"name":"BeanMatchersTest","sl":24}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_100":{"methods":[{"sl":36}],"name":"testHasValidGettersAndSettersFor","pass":true,"statements":[{"sl":38}]},"test_11":{"methods":[{"sl":76}],"name":"testHasValidBeanEquals","pass":true,"statements":[{"sl":78}]},"test_110":{"methods":[{"sl":86}],"name":"testHasValidBeanEqualsExcluding","pass":true,"statements":[{"sl":88}]},"test_115":{"methods":[{"sl":96}],"name":"testHasValidBeanToString","pass":true,"statements":[{"sl":98}]},"test_134":{"methods":[{"sl":81}],"name":"testHasValidBeanEqualsOnNonReflectedEquals","pass":true,"statements":[{"sl":83}]},"test_137":{"methods":[{"sl":61}],"name":"testHasValidBeanHashCode","pass":true,"statements":[{"sl":63}]},"test_146":{"methods":[{"sl":111}],"name":"shouldThrowExceptionOnBeanWithPropertyNeedingCustomValueGenerator","pass":true,"statements":[{"sl":113}]},"test_156":{"methods":[{"sl":41}],"name":"testBeanHasValidGettersAndSettersExcluding","pass":true,"statements":[{"sl":43}]},"test_157":{"methods":[{"sl":31}],"name":"testBeanHasValidGettersAndSettersFor","pass":true,"statements":[{"sl":33}]},"test_19":{"methods":[{"sl":56}],"name":"testHasValidGettersAndSetters","pass":true,"statements":[{"sl":58}]},"test_28":{"methods":[{"sl":101}],"name":"testHasValidBeanToStringExcluding","pass":true,"statements":[{"sl":103}]},"test_30":{"methods":[{"sl":66}],"name":"testHasValidBeanHashCodeFor","pass":true,"statements":[{"sl":68}]},"test_34":{"methods":[{"sl":91}],"name":"testHasValidBeanEqualsFor","pass":true,"statements":[{"sl":93}]},"test_35":{"methods":[{"sl":26}],"name":"testHasValidBeanConstructor","pass":true,"statements":[{"sl":28}]},"test_58":{"methods":[{"sl":46}],"name":"testHasValidGettersAndSettersExcluding","pass":true,"statements":[{"sl":48}]},"test_64":{"methods":[{"sl":71}],"name":"testHasValidBeanHashCodeExcluding","pass":true,"statements":[{"sl":73}]},"test_65":{"methods":[{"sl":116}],"name":"canRegisterCustomValueGenerator","pass":true,"statements":[{"sl":118},{"sl":119}]},"test_89":{"methods":[{"sl":51}],"name":"testBeanHasValidGettersAndSetters","pass":true,"statements":[{"sl":53}]},"test_90":{"methods":[{"sl":106}],"name":"testHasValidBeanToStringFor","pass":true,"statements":[{"sl":108}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [35], [], [35], [], [], [157], [], [157], [], [], [100], [], [100], [], [], [156], [], [156], [], [], [58], [], [58], [], [], [89], [], [89], [], [], [19], [], [19], [], [], [137], [], [137], [], [], [30], [], [30], [], [], [64], [], [64], [], [], [11], [], [11], [], [], [134], [], [134], [], [], [110], [], [110], [], [], [34], [], [34], [], [], [115], [], [115], [], [], [28], [], [28], [], [], [90], [], [90], [], [], [146], [], [146], [], [], [65], [], [65], [65], [], []]
