var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":16,"id":208,"methods":[{"el":7,"sc":5,"sl":5},{"el":11,"sc":5,"sl":9},{"el":15,"sc":5,"sl":13}],"name":"BeanMatchersException","sl":3}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_10":{"methods":[{"sl":5}],"name":"shouldThrowExceptionWhenNoGeneratorRegisteredForTypeAndTypeIsFinal","pass":true,"statements":[{"sl":6}]},"test_103":{"methods":[{"sl":9}],"name":"beanWithInvalidGetterShouldBeDiagnosed","pass":true,"statements":[{"sl":10}]},"test_106":{"methods":[{"sl":5}],"name":"shouldThrowExceptionIfSetterIsMissing","pass":true,"statements":[{"sl":6}]},"test_119":{"methods":[{"sl":5}],"name":"shouldThrowExceptionGivenCannotGenerateTwoDistinctValuesAfterXAttempts","pass":true,"statements":[{"sl":6}]},"test_124":{"methods":[{"sl":5}],"name":"getPropertyShouldThrowExceptionGivenPropertyDoesNotExistOnBean","pass":true,"statements":[{"sl":6}]},"test_127":{"methods":[{"sl":9}],"name":"beanWithoutNoArgsConstructorShouldNotMatch","pass":true,"statements":[{"sl":10}]},"test_141":{"methods":[{"sl":5}],"name":"shouldThrowExceptionOnBeanWithPropertyNeedingCustomValueGenerator","pass":true,"statements":[{"sl":6}]},"test_148":{"methods":[{"sl":5}],"name":"canCreateExceptionWithMessage","pass":true,"statements":[{"sl":6}]},"test_36":{"methods":[{"sl":5}],"name":"propertyTypeShouldThrowExceptionGivenPropertyDoesNotExistOnBean","pass":true,"statements":[{"sl":6}]},"test_40":{"methods":[{"sl":5}],"name":"beanWithMissingSetterShouldNotMatch","pass":true,"statements":[{"sl":6}]},"test_59":{"methods":[{"sl":5}],"name":"setPropertyShouldThrowExceptionGivenPropertyDoesNotExistOnBean","pass":true,"statements":[{"sl":6}]},"test_6":{"methods":[{"sl":5}],"name":"shouldThrowExceptionIfGetterIsMissing","pass":true,"statements":[{"sl":6}]},"test_61":{"methods":[{"sl":9}],"name":"canCreateExceptionWithMessageAndCause","pass":true,"statements":[{"sl":10}]},"test_67":{"methods":[{"sl":5}],"name":"beanWithMissingGetterShouldNotMatch","pass":true,"statements":[{"sl":6}]},"test_78":{"methods":[{"sl":13}],"name":"canCreateExceptionWithCause","pass":true,"statements":[{"sl":14}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [10, 106, 36, 141, 67, 40, 148, 6, 119, 124, 59], [10, 106, 36, 141, 67, 40, 148, 6, 119, 124, 59], [], [], [103, 127, 61], [103, 127, 61], [], [], [78], [78], [], []]
