var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":25,"id":427,"methods":[{"el":13,"sc":3,"sl":11},{"el":19,"sc":3,"sl":15},{"el":24,"sc":3,"sl":21}],"name":"InMemoryValueGeneratorRepository","sl":6}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_1":{"methods":[{"sl":21}],"name":"testHasValidBeanEqualsExcluding","pass":true,"statements":[{"sl":23}]},"test_10":{"methods":[{"sl":21}],"name":"testHasValidBeanToString","pass":true,"statements":[{"sl":23}]},"test_106":{"methods":[{"sl":21}],"name":"testHasValidGettersAndSettersFor","pass":true,"statements":[{"sl":23}]},"test_118":{"methods":[{"sl":21}],"name":"testHasValidGettersAndSettersExcluding","pass":true,"statements":[{"sl":23}]},"test_14":{"methods":[{"sl":11},{"sl":15},{"sl":21}],"name":"shouldThrowExceptionOnBeanWithPropertyNeedingCustomValueGenerator","pass":true,"statements":[{"sl":12},{"sl":17},{"sl":18},{"sl":23}]},"test_140":{"methods":[{"sl":21}],"name":"testHasValidBeanEqualsFor","pass":true,"statements":[{"sl":23}]},"test_145":{"methods":[{"sl":11},{"sl":21}],"name":"canRegisterCustomValueGenerator","pass":true,"statements":[{"sl":12},{"sl":23}]},"test_15":{"methods":[{"sl":21}],"name":"testHasValidGettersAndSetters","pass":true,"statements":[{"sl":23}]},"test_161":{"methods":[{"sl":11},{"sl":21}],"name":"canRegisterValueGenerator","pass":true,"statements":[{"sl":12},{"sl":23}]},"test_24":{"methods":[{"sl":21}],"name":"testHasValidBeanHashCode","pass":true,"statements":[{"sl":23}]},"test_34":{"methods":[{"sl":21}],"name":"testBeanHasValidGettersAndSettersFor","pass":true,"statements":[{"sl":23}]},"test_53":{"methods":[{"sl":11},{"sl":15},{"sl":21}],"name":"canRegisterValueGeneratorForTwoTypes","pass":true,"statements":[{"sl":12},{"sl":17},{"sl":18},{"sl":23}]},"test_76":{"methods":[{"sl":11},{"sl":21}],"name":"shouldNotRegisterValueGeneratorForDifferingType","pass":true,"statements":[{"sl":12},{"sl":23}]},"test_84":{"methods":[{"sl":21}],"name":"testBeanHasValidGettersAndSettersExcluding","pass":true,"statements":[{"sl":23}]},"test_85":{"methods":[{"sl":21}],"name":"testHasValidBeanEquals","pass":true,"statements":[{"sl":23}]},"test_90":{"methods":[{"sl":21}],"name":"testHasValidBeanEqualsOnNonReflectedEquals","pass":true,"statements":[{"sl":23}]},"test_96":{"methods":[{"sl":21}],"name":"testBeanHasValidGettersAndSetters","pass":true,"statements":[{"sl":23}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [], [161, 76, 145, 53, 14], [161, 76, 145, 53, 14], [], [], [53, 14], [], [53, 14], [53, 14], [], [], [106, 85, 96, 161, 84, 34, 76, 118, 10, 140, 145, 1, 53, 15, 90, 14, 24], [], [106, 85, 96, 161, 84, 34, 76, 118, 10, 140, 145, 1, 53, 15, 90, 14, 24], [], []]
