var clover = new Object();

// JSON: {classes : [{name, id, sl, el,  methods : [{sl, el}, ...]}, ...]}
clover.pageData = {"classes":[{"el":23,"id":425,"methods":[{"el":12,"sc":5,"sl":10},{"el":17,"sc":5,"sl":14},{"el":22,"sc":5,"sl":19}],"name":"InMemoryValueGeneratorRepository","sl":6}]}

// JSON: {test_ID : {"methods": [ID1, ID2, ID3...], "name" : "testXXX() void"}, ...};
clover.testTargets = {"test_116":{"methods":[{"sl":19}],"name":"testHasValidGettersAndSettersExcluding","pass":true,"statements":[{"sl":21}]},"test_117":{"methods":[{"sl":10},{"sl":19}],"name":"canRegisterValueGenerator","pass":true,"statements":[{"sl":11},{"sl":21}]},"test_12":{"methods":[{"sl":19}],"name":"testBeanHasValidGettersAndSetters","pass":true,"statements":[{"sl":21}]},"test_123":{"methods":[{"sl":19}],"name":"testHasValidBeanEqualsOnNonReflectedEquals","pass":true,"statements":[{"sl":21}]},"test_138":{"methods":[{"sl":19}],"name":"testHasValidBeanHashCode","pass":true,"statements":[{"sl":21}]},"test_141":{"methods":[{"sl":10},{"sl":14},{"sl":19}],"name":"shouldThrowExceptionOnBeanWithPropertyNeedingCustomValueGenerator","pass":true,"statements":[{"sl":11},{"sl":15},{"sl":16},{"sl":21}]},"test_157":{"methods":[{"sl":19}],"name":"testHasValidGettersAndSetters","pass":true,"statements":[{"sl":21}]},"test_21":{"methods":[{"sl":19}],"name":"testHasValidBeanEquals","pass":true,"statements":[{"sl":21}]},"test_31":{"methods":[{"sl":10},{"sl":14},{"sl":19}],"name":"canRegisterValueGeneratorForTwoTypes","pass":true,"statements":[{"sl":11},{"sl":15},{"sl":16},{"sl":21}]},"test_41":{"methods":[{"sl":10},{"sl":19}],"name":"shouldNotRegisterValueGeneratorForDifferingType","pass":true,"statements":[{"sl":11},{"sl":21}]},"test_58":{"methods":[{"sl":19}],"name":"testHasValidGettersAndSettersFor","pass":true,"statements":[{"sl":21}]},"test_60":{"methods":[{"sl":19}],"name":"testHasValidBeanToString","pass":true,"statements":[{"sl":21}]},"test_7":{"methods":[{"sl":19}],"name":"testHasValidBeanEqualsFor","pass":true,"statements":[{"sl":21}]},"test_77":{"methods":[{"sl":10},{"sl":19}],"name":"canRegisterCustomValueGenerator","pass":true,"statements":[{"sl":11},{"sl":21}]},"test_80":{"methods":[{"sl":19}],"name":"testHasValidBeanEqualsExcluding","pass":true,"statements":[{"sl":21}]},"test_82":{"methods":[{"sl":19}],"name":"testBeanHasValidGettersAndSettersFor","pass":true,"statements":[{"sl":21}]},"test_84":{"methods":[{"sl":19}],"name":"testBeanHasValidGettersAndSettersExcluding","pass":true,"statements":[{"sl":21}]}}

// JSON: { lines : [{tests : [testid1, testid2, testid3, ...]}, ...]};
clover.srcFileLines = [[], [], [], [], [], [], [], [], [], [], [77, 141, 117, 31, 41], [77, 141, 117, 31, 41], [], [], [141, 31], [141, 31], [141, 31], [], [], [58, 77, 82, 84, 7, 116, 141, 117, 157, 80, 123, 60, 31, 21, 12, 41, 138], [], [58, 77, 82, 84, 7, 116, 141, 117, 157, 80, 123, 60, 31, 21, 12, 41, 138], [], []]
